name: friendlystore
description: "다정한제철음식사전"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  flutter_secure_storage: ^8.0.0
  cloud_firestore: ^5.1.0
  url_launcher: ^6.3.0
  kakao_flutter_sdk: ^1.9.5
  provider: ^6.1.2
  flutter_local_notifications: ^17.2.1+2
  firebase_messaging: ^15.0.3
  permission_handler: ^10.2.0
  audioplayers: ^6.0.0
  vibration: ^1.9.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: AppleSDGothicNeo
      fonts:
        - asset: assets/fonts/AppleSDGothicNeoR.ttf
          weight: 400
        - asset: assets/fonts/AppleSDGothicNeoR.ttf
          weight: 500
        - asset: assets/fonts/AppleSDGothicNeoSB.ttf
          weight: 600
        - asset: assets/fonts/AppleSDGothicNeoB.ttf
          weight: 700
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf